test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -14,7 +14,7 @@ jobs:
         run: |
           echo "Failed to test 1"
           echo "Failed to test 2"
-          exit 1
+          [[ 1 eq 1 ]] && echo "faileeed" && exit 1
       - name: Dump GitHub context
         if: failure()
         env:
