Test another CI pipeline

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,10 +12,10 @@ jobs:
       - uses: actions/checkout@v2.1.0
       - name: Set env var
         run: |
-          echo "::set-env name=TEST_FILE_NAME::test-${{ github.sha }}"
-      - name: Create file
+          echo "Failed to test 1"
+          echo "Failed to test 2"
+          exit 1
+      - name: Send report
+        if: failure()
         run: |
-          mkdir temp
-          cd temp
-          touch $TEST_FILE_NAME
-          ls -la
+          echo "${{ toJson(job) }}"
